Provide schema file as command line arg
domoritz/csv2parquet pull request #74
Opened 2022-05-01 13:42 UTC by andyredhead

As discussed in issue #73, here is a first cut at enabling a schema file to be supplied as a command line arg.

It relies entirely upon the json schema handling provided by arrow, which means there can be unexpected outcomes if mistakes are made while defining the schema...

The main problem will be that it seems the columns in the json schema are applied in numeric order to the columns in the CSV. If the json schema omits a column, the column definitions will get misaligned, meaning that columns may end up with the wrong heading or there are (poorly reported) incompatibilities between the data in the CSV file and the type expected for the column (i.e. trying to push a float into an int).

These problems can largely be avoided by using the schema inference process to generate an initial schema file, which can be edited prior to running a full convert.

As there is a pretty straight forward way of getting most cases to work with the functionality as implemented here, this seems like a good place to start. (it's good enough for my needs at the moment anyway :) )

Note: I wrote this against Arrow/Parquet 9.1.0 and got it working, then raised the version of those dependencies to 12.0.0 (latest release) and everything continued to just compile and work.

2022-05-03 22:32 UTC, domoritz requested changes

2022-05-03 22:32 UTC, domoritz commented on src/main.rs
> +    /// {n}
why do we need this?

2022-05-03 22:32 UTC, domoritz commented on src/main.rs
> +    /// Make sure to have the same number of columns in your schema file as are in your CSV!
This is a very long comment. Did you write it or copy it from arrow? If the former, please revise heavily and shorten.

2022-05-03 22:32 UTC, domoritz commented on src/main.rs
> +    #[clap(short = 's', long, parse(from_os_str), value_hint = ValueHint::AnyPath)]
Instead of a path, I wonder whether it's better to expect a string instead of a file. What do you think?

2022-05-03 22:32 UTC, domoritz commented on src/main.rs
> +            // a schema definition file path has been provided, create schema from that
please remove comments that explain the what instead of the why (which is all of them)

2022-05-03 22:32 UTC, domoritz commented on src/main.rs
> +                    "Problem opening schema file: {:?}, message: {}",
```suggestion
                    "Error opening schema file: {:?}, message: {}",
```

2022-05-03 22:32 UTC, domoritz commented on src/main.rs
> +                    "Problem opening schema file: {:?}, message: {}",
Or actually we will remove this if we switch to string.

2022-05-03 22:32 UTC, domoritz commented on src/main.rs
> +                    "Problem reading schema json: {}",
```suggestion
                    "Error reading schema json: {}",
```

2022-05-03 22:32 UTC, domoritz commented on src/main.rs
> +                    "Problem inferring schema: {}",
```suggestion
                    "Error inferring schema: {}",
```

2022-05-03 22:32 UTC, domoritz commented on src/main.rs
> +            match arrow::csv::reader::infer_file_schema(
I don't see any changes to the code where we used to infer the schema. Instead of copying the logic, please refactor the code so we reuse the logic.

2022-05-03 22:32 UTC, domoritz commented on src/main.rs
> +    //let reader = builder.build(input)?;
Remove comments like this.

2022-05-03 22:32 UTC, domoritz commented on src/main.rs
> +    let reader = builder.build(input)?;
can we reuse the existing logic?

2022-05-04 17:43 UTC, andyredhead commented on src/main.rs
> +    /// {n}
Not sure what you mean by "this", if its the {n} it was to try and get clap to generate newlines, I've removed from the text anyway

2022-05-04 17:44 UTC, andyredhead commented on src/main.rs
> +    /// Make sure to have the same number of columns in your schema file as are in your CSV!
I wrote it. I've had another go, chopped out a lot of the text.

2022-05-04 18:22 UTC, andyredhead commented on src/main.rs
> +            match arrow::csv::reader::infer_file_schema(
The logic has changed.

In the first match statement of fn main gets a schema by either:
- reading it in from the defined schema file, which is the path taken if a schema file is provided on the command line
- inferring it from the source csv file, using "arrow::csv::reader::infer_file_schema"

NOTE: the original code uses "builder.infer_schema(opts.max_read_records)", whereas the new code is using an associated function on the reader struct.

At this point we don't yet have a configured reader (or even a reader builder).

We do have a schema which we can give to the reader builder in a few lines time, which leads into your comment further down about re-using the existing logic...

2022-05-04 18:36 UTC, andyredhead commented on src/main.rs
> +    let reader = builder.build(input)?;
Given that the logic around getting a schema has changed such that we've already got a schema without needing a Reader or ReaderBuilder, this seems to be the cleanest (and closest to the original logic) approach.

If we've got a defined schema file, we've read it and built the schema without touching the source csv, the input File hasn't been touched and is ready to read.

If we don't have a defined schema file and the max records is a value that lets us infer a schema, we've inferred a schema using the infer method on the CsvReader struct (rather than using the ReaderBuilder), the input File has been read and wound back to start (exactly as in the original code).

If we don't have a defined schema file and the max records is zero, we have a schema that's all strings, the input File is ready to read (exactly as in the original code).

If I've missed something, please try and point it out to me again :)

2022-05-06 23:30 UTC, domoritz approved these changes

2022-05-06 23:30 UTC, domoritz commented on src/main.rs
> +                ))),
```suggestion
                Err(error) => Err(ParquetError::General(format!(
                    "Error opening schema file: {:?}, message: {}",
                    schema_def_file_path, error
                ))),
```

2022-05-06 23:30 UTC, domoritz commented on src/main.rs
> +                    Err(schema_err) => Err(ParquetError::ArrowError(schema_err.to_string())),
```suggestion
                    Err(error) => Err(ParquetError::ArrowError(error.to_string())),
```

2022-05-06 23:30 UTC, domoritz commented on src/main.rs
> +                    Err(schema_err) => Err(ParquetError::ArrowError(schema_err.to_string())),
Does this work?

```suggestion
                    Err(error) => Err(error.into()),
```

2022-05-06 23:30 UTC, domoritz commented on src/main.rs
> +    //let reader = builder.build(input)?;
```suggestion
```

2022-05-06 23:30 UTC, domoritz commented on src/main.rs
> +                ))),
```suggestion
                Err(error) => Err(ParquetError::General(format!(
                    "Error inferring schema: {}",
                    error
                ))),
```

2022-05-07 18:32 UTC, andyredhead commented on src/main.rs
> +                    Err(schema_err) => Err(ParquetError::ArrowError(schema_err.to_string())),
Yes, it does (and its much more succinct :))

2022-05-08 13:25 UTC, domoritz approved these changes

2022-05-08 13:25 UTC, domoritz commented on src/main.rs
> +    /// The structure of schema json is shown in the source of: DataType fn from(json: &Value -> Result<DataType> in:
Please fix grammar and make it easier to understand.

2022-05-08 13:25 UTC, domoritz commented on src/main.rs
> +    /// Make sure your schema has the same number of columns as your CSV!
I don't think this is good here. It's an obvious statement and not usually what I expect to read in cli docs.

2022-05-11 22:37 UTC, domoritz commented on src/main.rs
> +    /// {n}
Yeah, I meant the {n}

2022-05-11 22:48 UTC, domoritz approved these changes

2022-05-11 22:48 UTC, domoritz commented on src/main.rs
> +    schema_def_file: Option<PathBuf>,
```suggestion
    schema_file: Option<PathBuf>,
```

2022-05-11 22:48 UTC, domoritz commented on src/main.rs
> +            let json_read_result: serde_json::Result<Value> = serde_json::from_reader(schema_file);
```suggestion
            let json: serde_json::Result<Value> = serde_json::from_reader(schema_file);
```

2022-05-11 22:48 UTC, domoritz commented on src/main.rs
> +                Ok((schema, _inferred_has_header)) => Ok(schema),
Should we use `_inferred_has_header`?

2022-05-11 22:48 UTC, domoritz commented on src/main.rs
> +    /// The structure of schema JSON is shown in the source of: DataType fn from(json: &Value -> Result<DataType> in: https://github.com/apache/arrow-rs/blob/master/arrow/src/datatypes/datatype.rs
```suggestion
    /// File with Arrow schema in JSON format.
```

I think we can keep this short and provide details in the readme instead.

2022-05-12 20:09 UTC, andyredhead commented on src/main.rs
> +    schema_def_file: Option<PathBuf>,
cool

2022-05-12 20:09 UTC, andyredhead commented on src/main.rs
> +            let json_read_result: serde_json::Result<Value> = serde_json::from_reader(schema_file);
cool

2022-05-12 20:10 UTC, andyredhead commented on src/main.rs
> +    /// The structure of schema JSON is shown in the source of: DataType fn from(json: &Value -> Result<DataType> in: https://github.com/apache/arrow-rs/blob/master/arrow/src/datatypes/datatype.rs
Yes, that makes sense.

2022-05-13 04:07 UTC, merged

2022-05-13 04:07 UTC, domoritz commented
Thank you for the implementation and the patience with my reviews. Could you send PRs for the related repos now? Once they are in, I will make a release.

2022-05-13 20:24 UTC, andyredhead commented
No worries, I appreciate you tolerating my bumbling newbie efforts.
Yes, I'll take a look at the related repos over the next few days.